import './globals.css'
import localFont from 'next/font/local'
import { Header } from '@/components/layout/Header/Header';

const SFProDisplay = localFont({
  src: '../../fonts/SF-Pro-Display-Regular.otf',

}); 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={SFProDisplay.className}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
